baseURL: "https://hirothreading.github.io/" 
title: David Murakami
pagination:
  pagerSize: 10
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

menu:
    main:
        - name: Research
          url: /research/
          weight: 1
        - name: Teaching
          url: /courses/
          weight: 2

params:
    description: "I am a macroeconomist in the Bank of England's Macro Modelling Division, and a PhD Candidate in Economics at the University of Milan and University of Pavia, supervised by Guido Ascari and co-supervised by Andrea Ferrero and Francesco Zanetti. I hold an MPhil in Economics from the University of Oxford and an MA in Economics from Keio University. I was a visiting PhD student at Bocconi University and the University of Oxford. I research monetary policy, financial frictions, and international macroeconomics."
    author: David Murakami
    dateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: David Murakami
          subtitle: "I am a macroeconomist in the Bank of England's Macro Modelling Division, and a PhD Candidate in Economics at the University of Milan and University of Pavia, supervised by Guido Ascari and co-supervised by Andrea Ferrero and Francesco Zanetti. I hold an MPhil in Economics from the University of Oxford and an MA in Economics from Keio University. I was a visiting PhD student at Bocconi University and the University of Oxford. I research monetary policy, financial frictions, and international macroeconomics."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: David Murakami
          buttons:
            - name: Research
              url: /research/
            - name: Teaching
              url: /courses/
    socialIcons:
        - name: CV
          url: "/David_Murakami_CV.pdf"
        - name: Email
          url: mailto:david.murakami@outlook.com
        - name: Location
          url: /location/
        - name: GitHub
          url: https://github.com/hirothreading?tab=repositories
        - name: LinkedIn
          url: https://www.linkedin.com/in/d-h-murakami/
        - name: Twitter
          url: https://x.com/hirothreading

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "David Murakami"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
